FROM node:16-alpine AS build
WORKDIR /app
COPY app/package*.json ./
RUN npm install --production     

COPY app/ .

FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app ./

EXPOSE 3000
CMD ["npm","start"]